teams:
  - name: lf-staff
    maintainers:
      - ryjones
      - jwagantall
    members:
      - thelinuxfoundation
  - name: aries-test
    maintainers:
      - ryjones
    members:
      - swcurran

repositories:
  - name: governance
    teams:
      lf-staff: maintain
    visibility: public
